def welcom():
    print("------------------Welcome to the Analysis Assistance Program------------------")
   # print("---------------------choose one out of the options given----------------------")
 #   print("                  1  <-- to do analysis on new file          ")
  #  print("                  2  <-- to do analysis of existing file          ")
def choi():
    print("------------------please choose between the following-------------------------")
    print("                  1  <-- heatmap generation          ")
    print("                  2  <-- line plot          ")
    print("                  3  <-- data description          ")
    print("                  4  <-- preprocessing of data          ")
    print("                  5  <-- box plot          ")
    print("                  6  <-- violin plot          ")
    print("                  7  <-- exit          ")
    print("------------------------------------------------------------------------------")
def logi():
    print("------------------------------------------------------------------------------")
    print("                  1  <-- login         ")
    print("                  2  <-- new account         ")
    print("------------------------------------------------------------------------------")
